name: Matirx Deployment
on: 
  push:
    branches:
      - master
jobs: 
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [12,14,16]
        include:  #we can include the values that run on single instace
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: #we can exclude the values that will not run in the instance.
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
  
